# Generated by Django 5.2.4 on 2025-07-31 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SinhVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_sinh_vien', models.CharField(max_length=20, unique=True)),
                ('ho_ten', models.CharField(max_length=50)),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=10)),
                ('ngay_sinh', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('so_dien_thoai', models.CharField(max_length=10)),
                ('dia_chi', models.TextField()),
                ('lop', models.CharField(max_length=20)),
                ('nganh', models.CharField(max_length=100)),
                ('khoa', models.CharField(max_length=100)),
            ],
        ),
    ]
